apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: my-goapp-api
  name: my-goapp-api
  namespace: my-goapp
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - env:
        - name: GO_ACTIVE_PROFILE
          value: dev
        image: {IMAGE}
        imagePullPolicy: Always
        name: go-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: harbor-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
